### ISSUE TITLE
Questions about this code

### ISSUE THREAD

**Issue by lefuturiste** [himanshuk32/Odometry--Automation-of-Mobile-Robot#1]
Hello,

I'm a hobbyist in robotic and I'm looking to do odometry for my 4 mecanum wheel holonomic robot.
My wheel configuration is 4 wheels all oriented toward the same direction:

![image](https://user-images.githubusercontent.com/20988163/76163080-89c03680-6143-11ea-84d1-b750b53437ac.png)

I use [REV Core hex motors](https://www.revrobotics.com/rev-41-1300/) which have a integrated quadratic encoder.
So I was wondering if I can use these encoders (at least 3 of theses) to do my odometry and known the position and the orientation of my robot.
I'm really interested in this repository here and my questions are:
- What is you encoder configuration ? I saw that you have 5 of them (1, 2, 3, x, y), why using so many ? and where are they located ?
- Do you think I can create a code to compute my position and orientation with only 3 encoders in my configuration that I described above ?

Thanks you very much in advance!

**Comment by himanshuk32** [comment]
Hi, 

First of all, sorry for the very late reply.

I will try to answer your questions. 
1. The code is made for omni-directional robot consisting of 3 omni wheels. The wheels are placed at the vertices of an equilateral triangle with each wheel's axis facing towards the center of the triangle. They are represented by the indices 1,2 and 3 in the code. In addition to this configuration, two rotary encoders (high precision) are placed at the center of the robot. They are perpendicular to each other and face in the robot's local X and Y. They are represented by x and y in the code. 

2. For the 4-wheeled mecanuum drive, you can compute the x and y position of the robot using the four wheels, provided the rotary encoders are highly accurate. You can compute the velocity of the robot using Forward Kinematics and then integrating the same would give you the X and Y position. But, you would need an IMU for estimating the orientation of the robot.
